feat: added basic configuration settings and static pages
isas2/testing-system pull request #1
Opened 2024-03-12 11:34 UTC by isas2

2024-03-12 15:00 UTC, VidgarVii requested changes

2024-03-12 15:00 UTC, VidgarVii commented on config/initializers/version.rb
> +    VERSION = '0.1.0'
про константы следующий момент:

"мутабельные" объекты (строки, хэши, массивы) рекомендуется `freeze`-ить, чтобы они были неизменяемыми
в противном случае константу, ссылающуюся на "мутабельный" объект,  можно изменить: `VERSION << '3.14..'`

2024-03-12 15:00 UTC, VidgarVii commented on public/about/author.html
> +</html>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-03-12 15:00 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :ru
чтобы не было ошибок в системе, надо еще добавить файл конфигураций в папку config/locales ru.yml. Содержание почти аналогичное как en.yml

2024-03-14 02:46 UTC, closed without merging

2024-03-14 02:47 UTC, isas2 commented
Исправления в следующем коммите