feat(db): added main models
isas2/testing-system pull request #3
Opened 2024-03-15 09:29 UTC by isas2

2024-03-15 15:15 UTC, VidgarVii requested changes

2024-03-15 15:15 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :user
ассоциации позже будут в курсе
пока лучше убери их из моделей, чтобы они не отвлекали. Тем более они объявлены не верно.
Нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

2024-03-15 15:15 UTC, VidgarVii commented on db/migrate/20240315090738_add_models_null_constraint.rb
> +    change_column_null(:categories, :title, false)
не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2024-03-15 15:15 UTC, VidgarVii commented on db/schema.rb
> +    t.integer "user_id", null: false
Где-то в начале уроков было описание проекта. Там говорилось, что у каждого вопроса будут варианты ответов, которые пользователь сможет выбрать. Получается, что ответ принадлежит вопросу, а не пользователю

2024-03-15 15:15 UTC, VidgarVii commented on db/schema.rb
> +    t.boolean "correct", default: false
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2024-03-15 15:15 UTC, VidgarVii commented on db/schema.rb
> +    t.index ["category_id"], name: "index_tests_on_category_id"
для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2024-03-15 15:15 UTC, VidgarVii commented on db/schema.rb
> +    t.integer "level", default: 0
null: false

2024-03-16 11:59 UTC, closed without merging

2024-03-16 11:59 UTC, isas2 commented
Fixed in next commit